-- begin CARSERVICE_CAR_SERVICE_CENTER
alter table CARSERVICE_CAR_SERVICE_CENTER add constraint FK_CARSERVICE_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references CARSERVICE_CITY(ID)^
alter table CARSERVICE_CAR_SERVICE_CENTER add constraint FK_CARSERVICE_CAR_SERVICE_CENTER_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID)^
create index IDX_CARSERVICE_CAR_SERVICE_CENTER_CITY on CARSERVICE_CAR_SERVICE_CENTER (CITY_ID)^
create index IDX_CARSERVICE_CAR_SERVICE_CENTER_CREATOR on CARSERVICE_CAR_SERVICE_CENTER (CREATOR_ID)^
-- end CARSERVICE_CAR_SERVICE_CENTER
-- begin CARSERVICE_REPAIR
alter table CARSERVICE_REPAIR add constraint FK_CARSERVICE_REPAIR_CENTER foreign key (CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID)^
alter table CARSERVICE_REPAIR add constraint FK_CARSERVICE_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references CARSERVICE_EMPLOYEE(ID)^
create index IDX_CARSERVICE_REPAIR_CENTER on CARSERVICE_REPAIR (CENTER_ID)^
create index IDX_CARSERVICE_REPAIR_EMPLOYEE on CARSERVICE_REPAIR (EMPLOYEE_ID)^
-- end CARSERVICE_REPAIR
-- begin CARSERVICE_EMPLOYEE
alter table CARSERVICE_EMPLOYEE add constraint FK_CARSERVICE_EMPLOYEE_CENTER foreign key (CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID)^
create index IDX_CARSERVICE_EMPLOYEE_CENTER on CARSERVICE_EMPLOYEE (CENTER_ID)^
-- end CARSERVICE_EMPLOYEE
-- begin CARSERVICE_INDIVIDUAL
alter table CARSERVICE_INDIVIDUAL add constraint FK_CARSERVICE_INDIVIDUAL_ID foreign key (ID) references CARSERVICE_CUSTOMER(ID)^
-- end CARSERVICE_INDIVIDUAL
-- begin CARSERVICE_COMPANY
alter table CARSERVICE_COMPANY add constraint FK_CARSERVICE_COMPANY_ID foreign key (ID) references CARSERVICE_CUSTOMER(ID)^
-- end CARSERVICE_COMPANY
-- begin CARSERVICE_CENTER_CUSTOMER_LINK
alter table CARSERVICE_CENTER_CUSTOMER_LINK add constraint FK_CENCUS_CUSTOMER foreign key (CUSTOMER_ID) references CARSERVICE_CUSTOMER(ID)^
alter table CARSERVICE_CENTER_CUSTOMER_LINK add constraint FK_CENCUS_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID)^
-- end CARSERVICE_CENTER_CUSTOMER_LINK
-- begin CARSERVICE_CITY
create unique index IDX_CARSERVICE_CITY_UK_NAME on CARSERVICE_CITY (NAME) where DELETE_TS is null ^
-- end CARSERVICE_CITY
